### ISSUE TITLE
Missing lodash

### ISSUE THREAD

**Issue by JZ-at-TP** [bevacqua/grunt-verify-app#1]
When using the module I get the following error.

Running "verify_app:server" (verify_app) task
Warning: Cannot find module 'lodash' Use --force to continue.

**Comment by bevacqua** [comment]
do `npm i grunt-verify-app`, rather than cloning the repository

**Comment by JZ-at-TP** [comment]
I had included the repository in my applications package.json file. When I run npm install is adds grunt-verify-app to my node_modules folder. but when I tried to use it in my applications gruntfile.js I got the error. Should I be using it some other way?
